version: "3.7"
services:
  ginatells-ui:
    build:
      context: ../ginatells-ui
      dockerfile: Dockerfile.production
    ports:
      - "3000:3000"
  ginatells-movies-api:
    build: ../movies-api
    ports:
      - "5000:80"
